name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Python ${{ matrix.versions.python }}
    runs-on: ${{ matrix.versions.os }}
    strategy:
      fail-fast: false
      matrix:
        versions:
          - python: "3.6"
            os: ubuntu-20.04
          - python: "3.7"
            os: ubuntu-22.04
          - python: "3.8"
            os: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.python }}
      - run: pip install -e .
      - run: python setup.py test
